routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    // Authentication Routes...
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/command', 'CommandController');
    Route::resource('/cabang', 'CabangController');
    Route::resource('/panel', 'PanelUserController');
    Route::resource('/botuser', 'BotUserController');
    Route::resource('/log', 'LogController');
    Route::resource('/role', 'RoleController');
    Route::resource('/telegramconfig', 'TelegramConfigController');
    Route::get('/bot_activate', 'TelegramConfigController@bot_activate');
    Route::get('/change_token', 'TelegramConfigController@change_token');
});

Route::match(['get', 'post'], '/core', 'Telegram\CoreController@handle')->name('core');
Route::match(['get', 'post'], '/coreapi', 'Telegram\CoreController@coreAPI')->name('coreapi');

// file handle
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('app/output/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

resources/views/footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <div class="text-right">
        <strong>Copyright &copy; {{ date("Y") }} <a href="https://www.swamedia.co.id/">Swamedia Informatika</a>.</strong>
    </div>
</footer>

</div>
<!-- ./wrapper -->

<!-- Global Script -->
<script>
    $( document ).ready(function() {
        //Initialize Select2 Elements
        $('.select2').select2()

        // datatable
        $('#data').DataTable({
            'paging'      : true,
            'lengthChange': false,
            'searching'   : true,
            'ordering'    : true,
            'info'        : true,
            'autoWidth'   : false,
        });
    });
</script>

</html>

resources/views/header.blade.php
<!DOCTYPE html>

<?php
    $tmp    = Request::segments();
    $header = ucfirst(end($tmp));
?>

<html>
    <head lang="{{ str_replace('_', '-', app()->getLocale()) }}">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{{ config('app.name', 'Laravel') }} | {{ $header }}</title>
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <link rel="shortcut icon" href="{{ asset('img/telegram.png') }}">

        <link rel="stylesheet" href="{{ asset("bower_components/bootstrap/dist/css/bootstrap.min.css") }}">
        <link rel="stylesheet" href="{{ asset("bower_components/font-awesome/css/font-awesome.min.css") }}">
        <link rel="stylesheet" href="{{ asset("bower_components/Ionicons/css/ionicons.min.css") }}">
        <link rel="stylesheet" href="{{ asset("bower_components/admin-lte/dist/css/AdminLTE.min.css") }}">
        <link rel="stylesheet" href="{{ asset("bower_components/admin-lte/dist/css/skins/skin-blue.min.css") }}">
        <link rel="stylesheet" href="{{ asset("bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css") }}">
        <!-- iCheck for checkboxes and radio inputs -->
        <link rel="stylesheet" href="{{ asset("bower_components/admin-lte/plugins/iCheck/all.css") }}">
        <!-- Select2 -->
        <link rel="stylesheet" href="{{ asset("bower_components/select2/dist/css/select2.min.css") }}">
        <!-- Toggle Button -->
        <link rel="stylesheet" href="{{ asset("bower_components/bootstrap-toggle/css/bootstrap4-toggle.min.css") }}">

        <style type="text/css">
            .table th {
                text-align: center;
            }
        </style>

        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    </head>

    <!-- REQUIRED JS SCRIPTS -->

    <!-- jQuery 3 -->
    <script src="{{ asset("bower_components/jquery/dist/jquery.min.js") }}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{{ asset("bower_components/bootstrap/dist/js/bootstrap.min.js") }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset("bower_components/admin-lte/dist/js/adminlte.min.js") }}"></script>
    <!-- DataTables -->
    <script src="{{ asset("bower_components/datatables.net/js/jquery.dataTables.min.js") }}"></script>
    <script src="{{ asset("bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js") }}"></script>
    <!-- SlimScroll -->
    <script src="{{ asset("bower_components/jquery-slimscroll/jquery.slimscroll.min.js") }}"></script>
    <!-- FastClick -->
    <script src="{{ asset("bower_components/fastclick/lib/fastclick.js") }}"></script>
    <!-- iCheck 1.0.1 -->
    <script src="{{ asset("bower_components/admin-lte/plugins/iCheck/icheck.min.js") }}"></script>
    <!-- Select2 -->
    <script src="{{ asset("bower_components/select2/dist/js/select2.full.min.js") }}"></script>
    <!-- Toggle Button -->
    <script src="{{ asset("bower_components/bootstrap-toggle/js/bootstrap4-toggle.min.js") }}"></script>

    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">

            <!-- Main Header -->
            <header class="main-header">

                <!-- Logo -->
                <a href="{{ route('home') }}" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>C</b>Bot</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Chat</b>Bot Panel</span>
                </a>

                <!-- Header Navbar -->
                <nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- Notifications: style can be found in dropdown.less -->
                            <li class="dropdown notifications-menu">
                                {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown">--}}
                                    {{--<i class="fa fa-bell-o"></i>--}}
                                    {{--<span class="label label-warning">10</span>--}}
                                {{--</a>--}}
                                <ul class="dropdown-menu">
                                    <li class="header">You have 10 notifications</li>
                                    <li>
                                        <!-- inner menu: contains the actual data -->
                                        <ul class="menu">
                                            <li>
                                                <a href="#">
                                                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#">
                                                    <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                                                    page and may cause design problems
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#">
                                                    <i class="fa fa-users text-red"></i> 5 new members joined
                                                </a>
                                            </li>

                                            <li>
                                                <a href="#">
                                                    <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                                                </a>
                                            </li>
                                            <li>
                                                <a href="#">
                                                    <i class="fa fa-user text-red"></i> You changed your username
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="footer"><a href="#">View all</a></li>
                                </ul>
                            </li>
                            <!-- Tasks: style can be found in dropdown.less -->
                            <!-- User Account Menu -->
                            <li class="dropdown user user-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <!-- The user image in the navbar-->
                                    {{--<img src="{{ asset("bower_components/admin-lte/dist/img/user2-160x160.jpg") }}" class="user-image" alt="User Image">--}}
                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                    <span class="hidden-xs">{{ ucfirst(Auth::user()->name) }}</span>
                                </a>
                                <ul class="dropdown-menu">
                                    {{--<!-- The user image in the menu -->--}}
                                    {{--<li class="user-header">--}}
                                        {{--<img src="{{ asset("bower_components/admin-lte/dist/img/user2-160x160.jpg") }}" class="img-circle" alt="User Image">--}}

                                        {{--<p>--}}
                                            {{--{{ Auth::user()->name }}--}}
                                        {{--</p>--}}
                                    {{--</li>--}}

                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="#" class="btn btn-default btn-flat">Profile</a>
                                        </div>
                                        <div class="pull-right">
                                            <a href="{{ route('logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                                {{ __('Logout') }}
                                            </a>
                                        </div>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            @csrf
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>

resources/views/home.blade.php
@extends('main')

@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Home
        </h1>
        <br>
        <ol class="breadcrumb">
            <?php $segments = ''; ?>
            @foreach(Request::segments() as $segment)
                <?php $segments .= '/'.$segment; ?>
                <li>
                    <a href="{{ $segments }}"><i>{{ ucfirst($segment) }}</i></a>
                </li>
            @endforeach
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">
            {{--<div class="box-header with-border">--}}
                {{--<h3 class="box-title">Title</h3>--}}

                {{--<div class="box-tools pull-right">--}}
                    {{--<button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"--}}
                         {{--title="Collapse">--}}
                        {{--<i class="fa fa-minus"></i></button>--}}
                    {{--<button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">--}}
                        {{--<i class="fa fa-times"></i></button>--}}
                {{--</div>--}}
            {{--</div>--}}
            <div class="box-body">
                {{ 'home' }}
            </div>
            <!-- /.box-body -->
            {{--<div class="box-footer">--}}
                {{--Footer--}}
            {{--</div>--}}
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->

    </section>
    <!-- /.content -->
</div>
@endsection

resources/views/main.blade.php
<!-- Header -->
@include('header')

<!-- Sidebar -->
@include('sidebar')

<!-- Content -->
@yield('content')

<!-- Footer -->
@include('footer')

resources/views/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="{{ (request()->is('home*')) ? 'active' : '' }}">
                <a href="{{ route('home') }}">
                    <i class="fa fa-home"></i> <span>Home</span>
                </a>
            </li>
            <li class="{{ (request()->is('bot/*')) ? 'active' : '' }}">
                <a href="{{ route('home') }}">
                    <i class="fa fa-telegram"></i> <span>Bot</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-folder-o"></i> <span>Master</span>
                    <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ (request()->is('command*')) ? 'active' : '' }}">
                        <a href="{{ route('command.index') }}">
                            <i class="fa fa-{{ (request()->is('command*')) ? 'dot-' : '' }}circle-o"></i> Command
                        </a>
                    </li>
                    <li class="{{ (request()->is('role*')) ? 'active' : '' }}">
                        <a href="{{ route('role.index') }}">
                            <i class="fa fa-{{ (request()->is('role*')) ? 'dot-' : '' }}circle-o"></i> Role
                        </a>
                    </li>
                    <li class="{{ (request()->is('botuser*')) ? 'active' : '' }}">
                        <a href="{{ route('botuser.index') }}">
                            <i class="fa fa-{{ (request()->is('botuser*')) ? 'dot-' : '' }}circle-o"></i> User Bot
                        </a>
                    </li>
                    <li class="{{ (request()->is('panel*')) ? 'active' : '' }}">
                        <a href="{{ route('panel.index') }}">
                            <i class="fa fa-{{ (request()->is('panel*')) ? 'dot-' : '' }}circle-o"></i> User Panel
                        </a>
                    </li>
                    <li class="{{ (request()->is('cabang*')) ? 'active' : '' }}">
                        <a href="{{ route('cabang.index') }}">
                            <i class="fa fa-{{ (request()->is('cabang*')) ? 'dot-' : '' }}circle-o"></i> Cabang
                        </a>
                    </li>
                </ul>
            </li>
            <li class="{{ (request()->is('log*')) ? 'active' : '' }}">
                <a href="{{ route('log.index') }}">
                    <i class="fa fa-clipboard"></i> <span>Log</span>
                </a>
            </li>
            <li class="{{ (request()->is('telegramconfig*')) ? 'active' : '' }}">
                <a href="{{ route('telegramconfig.index') }}">
                    <i class="fa fa-toggle-on"></i> <span>Config</span>
                </a>
            </li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

<script>
    // for treeview
    if ($('ul.treeview-menu li').hasClass("active")) {
        $('ul.treeview-menu').parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');
    }
</script>