routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    // Authentication Routes...
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/command', 'CommandController');
    Route::resource('/cabang', 'CabangController');
    Route::resource('/panel', 'PanelUserController');
    Route::resource('/botuser', 'BotUserController');
    Route::resource('/log', 'LogController');
    Route::resource('/role', 'RoleController');
    Route::resource('/telegramconfig', 'TelegramConfigController');
    Route::get('/bot_activate', 'TelegramConfigController@bot_activate');
    Route::get('/change_token', 'TelegramConfigController@change_token');
});

Route::match(['get', 'post'], '/core', 'Telegram\CoreController@handle')->name('core');
Route::match(['get', 'post'], '/coreapi', 'Telegram\CoreController@coreAPI')->name('coreapi');

// file handle
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('app/output/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    // connection
    protected $connection = 'mysql';
    // table name
    protected $table = 'role';
    // primary key
    public $primaryKey = 'id';
    // timestamps
    public $timestamps = true;

    protected $fillable = [
        'created_by',
        'created_at',
        'updated_by',
        'updated_at',
        'name',
        'status'
    ];
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\BotUser;
use App\Lib\Lib;
use App\Repositories\BotUserRepository;
use App\Repositories\RoleRepository;
use App\Role;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    protected $role, $lib;

    public function __construct(Role $role)
    {
        $this->role    = new RoleRepository($role);
        $this->lib     = new Lib();
    }

    public function index()
    {
        try
        {
            $data['list'] = $this->role->all();

            return view('role/list', $data);
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }

    public function create()
    {
        try
        {
            return view('role/form');
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }

    public function store(Request $request)
    {
        try
        {
            $validator = Validator::make($request->all(), [
                'name' => 'required'
            ]);

            if ($validator->fails()) return redirect()->back()->withErrors($validator)->withInput();

            $data = [
                'created_by'  => Auth::id(),
                'created_at'  => $this->lib->dateNow(),
                'updated_by'  => Auth::id(),
                'updated_at'  => $this->lib->dateNow(),
                'name'        => $request['name'],
                'status'      => $request['status']
            ];

            if ($response = $this->role->create($data))
            {
                return redirect('/role')->with('success', 'Bot user role has been added');
            }
            else
            {
                return redirect()->back()->withErrors($response)->withInput();
            }
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }

    public function show($id)
    {
        try
        {
            $data['data'] = $this->role->show($id);

            return $data;
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }

    public function edit($id)
    {
        try
        {
            $data['data'] = $this->role->show($id);

            return view('role/form', $data);
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }

    public function update(Request $request, $id)
    {
        try
        {
            $validator = Validator::make($request->all(), [
                'name' => 'required'
            ]);

            if ($validator->fails()) return redirect()->back()->withErrors($validator)->withInput();

            $data = [
                'updated_by'  => Auth::id(),
                'updated_at'  => $this->lib->dateNow(),
                'name'        => $request['name'],
                'status'      => $request['status']
            ];

            if ($response = $this->role->update($data, $id))
            {
                return redirect('/role')->with('success', 'Bot user role has been updated Successfully');
            }
            else
            {
                return redirect()->back()->withErrors($response)->withInput();
            }
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }

    public function destroy($id)
    {
        try
        {
            if ($response = $this->role->delete($id))
            {
                return redirect('/role')->with('success', 'Bot user role has been deleted Successfully');
            }
            else
            {
                return redirect('/role')->withErrors($response)->withInput();
            }
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }
}

resources/views/role/form.blade.php
@extends('main')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <i class="fa fa-dot-circle-o"></i> {{ isset($data['id']) ? "Edit" : "Create" }} Bot User Role
            </h1>
            <br>
            <ol class="breadcrumb">
                <?php $segments = ''; ?>
                @foreach(Request::segments() as $segment)
                    <?php $segments .= '/'.$segment; ?>
                    <li>
                        <a href="{{ $segments }}"><i>{{ ucfirst($segment) }}</i></a>
                    </li>
                @endforeach
            </ol>
        </section>
        <!-- Main content -->
        <section class="content container-fluid">
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <h4><i class="icon fa fa-close"></i>Failed</h4>
                                {{ $error }}
                            </div>
                        </div>
                    </div>
            @endforeach
        @endif
        <!-- Content -->
            <div class='row'>
                <div class="center-block col-md-8" style="float: none;">
                    <!-- Horizontal Form -->
                    <div class="box box-success">
                        <div class="box-header with-border">
                            <h3 class="box-title">Form</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form class="form-horizontal" method="POST" action="{{ isset($data['id']) ? route('role.update', $data['id']) : route('role.store') }}">
                            @if (isset($data['id']))
                                @method('PATCH')
                            @endif

                            @csrf
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="name" class="col-sm-3 control-label">Name</label>

                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ @$data['name'] }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="status" class="col-sm-3 control-label">Status</label>

                                    <div class="col-sm-9" style="bottom: -6px;">
                                        <!-- radio -->
                                        <label style="min-width: 130px;">
                                            <input type="radio" name="status" class="minimal" value="1" {{ @$data['status'] == 1 ? 'checked' : '' }}>
                                            Aktif
                                        </label>
                                        <label>
                                            <input type="radio" name="status" class="minimal" value="0" {{ @$data['status'] == 0 ? 'checked' : '' }}>
                                            Non Aktif
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-success pull-right">{{ isset($data['id']) ? "Save" : "Submit" }}</button>
                            </div>
                            <!-- /.box-footer -->
                        </form>
                    </div>
                </div>

            </div><!-- /.row -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <script>
        // iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-green',
            radioClass   : 'iradio_minimal-green'
        })
    </script>
@endsection

resources/views/role/list.blade.php
@extends('main')

@section('content')
    <style>
        .deleteForm {
            all: unset;
        }

        .example-modal .modal {
            position: relative;
            top: auto;
            bottom: auto;
            right: auto;
            left: auto;
            display: block;
            z-index: 1;
        }

        .example-modal .modal {
            background: transparent !important;
        }
    </style>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <i class="fa fa-dot-circle-o"></i> Bot User Role
            </h1>
            <br>
            <ol class="breadcrumb">
                <?php $segments = ''; ?>
                @foreach(Request::segments() as $segment)
                    <?php $segments .= '/'.$segment; ?>
                    <li>
                        <a href="{{ $segments }}"><i>{{ ucfirst($segment) }}</i></a>
                    </li>
                @endforeach
            </ol>
        </section>
        <!-- Main content -->
        <section class="content container-fluid">

            @if(session()->get('success'))
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4><i class="icon fa fa-check"></i>Success</h4>
                            {{ session()->get('success') }}
                        </div>
                    </div>
                </div>
            @endif

            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <h4><i class="icon fa fa-close"></i>Failed</h4>
                                {{ $error }}
                            </div>
                        </div>
                    </div>
                @endforeach
            @endif

            <!-- Content -->
            <div class='row'>
                <div class='col-md-12'>
                    <!-- Box -->
                    <div class="box box-default">
                        <div class="box-header with-border">
                            <div class="col-md-10">

                            </div>
                            <div class="col-md-2">
                                <a href="{{ route('role.create') }}" class="btn btn-block btn-success"><i class="fa fa-plus"></i> Add Data</a>
                            </div>
                        </div>
                        <div class="box-body">
                            <table id="data" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th width="5%">#</th>
                                    <th>Name</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {{--Data--}}
                                <?php $i = 1 ?>
                                @foreach($list as $key => $data)
                                    <tr>
                                        <td class="text-center">{{ $i++ }}</td>
                                        <td>{{ $data['name'] }}</td>
                                        <td class="text-center"><span class="label bg-{{ $data['status']==1? 'green' : 'red' }}">{{ $data['status']==1? 'Active' : 'Non Active' }}</span></td>
                                        <td class="text-center">
                                            <button class="btn btn-sm btn-info detailPage" data-toggle="modal" data-target="#modal-default" data_id="{{ $data['id'] }}"><i class="fa fa-info-circle"></i></button>
                                            <a href="{{ route('role.edit', $data['id']) }}" class="btn btn-sm btn-primary"><i class="fa fa-pencil-square-o"></i></a>
                                            <form class="deleteForm" action="{{ route('role.destroy', $data['id']) }}" row="{{ $data['name'] }}" method="POST">
                                                @method('DELETE')
                                                @csrf
                                                <button class="btn btn-sm btn-danger" id="btn-form"><i class="fa fa-trash-o"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                {{--End Data--}}
                                </tbody>
                            </table>
                        </div><!-- /.box-body -->

                    </div><!-- /.box -->
                </div><!-- /.col -->

            </div><!-- /.row -->

            <div class="modal fade" id="modal-default">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title"></h4>
                        </div>
                        <div class="modal-body">
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="name" class="col-sm-3 control-label">Name</label>

                                    <div class="col-sm-9">
                                        <p id="name" class="control-label">Name</p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="status" class="col-sm-3 control-label">Status</label>

                                    <div class="col-sm-9">
                                        <span id="status" class="label"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">

                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <script>
        jQuery(document).ready(function(){
            jQuery('.detailPage').click(function(e){
                e.preventDefault();
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                    }
                });
                jQuery.ajax({
                    url: "{{ url('role') }}" + "/" + $(this).attr('data_id'),
                    method: 'GET',
                    success: function(result) {
                        console.log(result);
                        $('.modal-title').text("Detail Bot User Role");
                        $('#name').text(result.data.name ? result.data.name : '-');
                        if (result.data.status === 1) {
                            $('#status').text("Active");
                            $('#status').addClass('bg-green');
                        } else {
                            $('#status').text("Non Active");
                            $('#status').addClass('bg-red');
                        }

                    }
                });
            });
        });

        $(".deleteForm").on("submit", function(){
            return confirm("Are you sure permanently delete " + this.getAttribute("row") + " ?");
        });
    </script>
@endsection