routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
    // Authentication Routes...
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('/command', 'CommandController');
    Route::resource('/cabang', 'CabangController');
    Route::resource('/panel', 'PanelUserController');
    Route::resource('/botuser', 'BotUserController');
    Route::resource('/log', 'LogController');
    Route::resource('/role', 'RoleController');
    Route::resource('/telegramconfig', 'TelegramConfigController');
    Route::get('/bot_activate', 'TelegramConfigController@bot_activate');
    Route::get('/change_token', 'TelegramConfigController@change_token');
});

Route::match(['get', 'post'], '/core', 'Telegram\CoreController@handle')->name('core');
Route::match(['get', 'post'], '/coreapi', 'Telegram\CoreController@coreAPI')->name('coreapi');

// file handle
Route::get('storage/{filename}', function ($filename)
{
    $path = storage_path('app/output/' . $filename);

    if (!File::exists($path)) {
        abort(404);
    }

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

app/BotUser.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BotUser extends Model
{
    // connection
    protected $connection = 'mysql';
    // table name
    protected $table = 'bot_user';
    // primary key
    public $primaryKey = 'id';
    // timestamps
    public $timestamps = true;

    protected $fillable = [
        'created_by', 'updated_by', 'name', 'username', 'password', 'telegram_id', 'role_id', 'status'
    ];
}

app/Http/Controllers/BotUserController.php
<?php

namespace App\Http\Controllers;

use App\BotUser;
use App\Lib\Lib;
use App\Repositories\BotUserRepository;
use App\Repositories\RoleRepository;
use App\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Crypt;

class BotUserController extends Controller
{
    protected $botuser, $lib, $role;

    public function __construct(BotUser $botuser, Role $role)
    {
        $this->botuser = new BotUserRepository($botuser);
        $this->role    = new RoleRepository($role);
        $this->lib     = new Lib();
    }

    public function index()
    {
        try
        {
            $data['list'] = $this->botuser->all();
            $data['command'] = $this->role->all();

            return view('botUser/list', $data);
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }

    }

    public function create()
    {
        try
        {
            $data['role']['data']      = $this->role->all()->where('status', 1);
            $data['role']['countData'] = $this->role->all()->count();

            return view('botUser/form', $data);
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }

    public function store(Request $request)
    {
        try
        {
            $validator = Validator::make($request->all(), [
                'name'             => 'required',
                'username'         => 'required|unique:bot_user',
                'password'         => 'required',
                'confirm_password' => 'required',
                'role_id'          => 'required',
                'telegram_id'      => 'required',
            ]);

            if ($validator->fails()) return redirect()->back()->withErrors($validator)->withInput();

            if ($request['password'] != $request['confirm_password']) return redirect()->back()->withErrors("Confirm password is not valid")->withInput();

            if ($this->botuser->all()->where('telegram_id', $request['telegram_id'])->count() != 0) return redirect()->back()->withErrors("your telegram account is already registered")->withInput();

            if ($this->botuser->all()->where('username', $request['username'])->count() != 0) return redirect()->back()->withErrors("username " . $request['username'] . " is already exsist")->withInput();

            if (strlen($request['password']) < 8) return redirect()->back()->withErrors("password must be 8-16 characters")->withInput();

            $data = [
                'created_by'  => Auth::id(),
                'created_at'  => $this->lib->dateNow(),
                'updated_by'  => Auth::id(),
                'updated_at'  => $this->lib->dateNow(),
                'name'        => $request['name'],
                'username'    => $request['username'],
                'password'    => Crypt::encrypt($request['password']),
                'role_id'     => $request['role_id'],
                'telegram_id' => $request['telegram_id'],
                'status'      => 0
            ];

            if ($response = $this->botuser->create($data))
            {
                return redirect('/botuser')->with('success', 'Bot user has been added');
            }
            else
            {
                return redirect()->back()->withErrors($response)->withInput();
            }
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }

    public function show($id)
    {
        try
        {
            $command                 = $this->role->all();
            $data['data']            = $this->botuser->show($id);
            $data['data']['role_id'] = $command->firstWhere('id', $data['data']['role_id'])['name'];

            return $data;
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }

    }

    public function edit($id)
    {
        try
        {
            $data['data']              = $this->botuser->show($id);
            $data['role']['data']      = $this->role->all()->where('status', 1);
            $data['role']['countData'] = $this->role->all()->count();

            return view('botUser/form', $data);
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }

    public function update(Request $request, $id)
    {
        try
        {
            $plain = 0;

            if ($request['password'] == null && $request['confirm_password'] == null)
            {
                $plain                       = 1;
                $origin                      = $this->botuser->all()->firstWhere('id', $id);
                $request['password']         = $origin['password'];
                $request['confirm_password'] = $origin['password'];
            }

            $validator = Validator::make($request->all(), [
                'name'             => 'required',
                'username'         => 'required|unique:bot_user,username, ' .$id. ',id',
                'password'         => 'required',
                'confirm_password' => 'required',
                'status'           => 'required',
                'role_id'          => 'required',
                'telegram_id'      => 'required',
            ]);

            if ($validator->fails()) return redirect()->back()->withErrors($validator)->withInput();

            if ($request['password'] != $request['confirm_password']) return redirect()->back()->withErrors("Confirm password is not valid")->withInput();

            if (strlen($request['password']) < 8) return redirect()->back()->withErrors("password must be 8-16 characters")->withInput();

            $data = [
                'updated_by'  => Auth::id(),
                'updated_at'  => $this->lib->dateNow(),
                'name'        => $request['name'],
                'username'    => $request['username'],
                'password'    => $plain == 1 ? $request['password'] : Crypt::encrypt($request['password']),
                'role_id'     => $request['role_id'],
                'telegram_id' => $request['telegram_id'],
                'status'      => $request['status']
            ];

            if ($response = $this->botuser->update($data, $id))
            {
                return redirect('/botuser')->with('success', 'Bot user has been updated Successfully');
            }
            else
            {
                return redirect()->back()->withErrors($response)->withInput();
            }
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }

    public function destroy($id)
    {
        try
        {
            if ($response = $this->botuser->delete($id))
            {
                return redirect('/botuser')->with('success', 'Bot user has been deleted Successfully');
            }
            else
            {
                return redirect('/botuser')->withErrors($response)->withInput();
            }
        }
        catch (\Exception $exception)
        {
            report($exception);

            return false;
        }
    }
}

resources/views/botUser/form.blade.php
@extends('main')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <i class="fa fa-dot-circle-o"></i> {{ isset($data['id']) ? "Edit" : "Create" }} Bot User
            </h1>
            <br>
            <ol class="breadcrumb">
                <?php $segments = ''; ?>
                @foreach(Request::segments() as $segment)
                    <?php $segments .= '/'.$segment; ?>
                    <li>
                        <a href="{{ $segments }}"><i>{{ ucfirst($segment) }}</i></a>
                    </li>
                @endforeach
            </ol>
        </section>
        <!-- Main content -->
        <section class="content container-fluid">
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <h4><i class="icon fa fa-close"></i>Failed</h4>
                                {{ $error }}
                            </div>
                        </div>
                    </div>
            @endforeach
        @endif
        <!-- Content -->
            <div class='row'>
                <div class="center-block col-md-8" style="float: none;">
                    <!-- Horizontal Form -->
                    <div class="box box-success">
                        <div class="box-header with-border">
                            <h3 class="box-title">Form</h3>
                        </div>
                        <!-- /.box-header -->
                        <!-- form start -->
                        <form class="form-horizontal" method="POST" action="{{ isset($data['id']) ? route('botuser.update', $data['id']) : route('botuser.store') }}">
                            @if (isset($data['id']))
                                @method('PATCH')
                            @endif

                            @csrf
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="name" class="col-sm-3 control-label">Name</label>

                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ @$data['name'] }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="username" class="col-sm-3 control-label">Username</label>

                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" id="username" name="username" placeholder="Username" value="{{ @$data['username'] }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="password" class="col-sm-3 control-label">Password</label>

                                    <div class="col-sm-9">
                                        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="confirm_password" class="col-sm-3 control-label">Confirm Password</label>

                                    <div class="col-sm-9">
                                        <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Confirm Password">
                                        @if (isset($data['id']))
                                            <p class="help-block"><i>if you don't want to change the password, ignore the input <b>password</b> and input <b>confirm password</b></i></p>
                                        @endif
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="status" class="col-sm-3 control-label">Role</label>

                                    <div class="col-sm-9" style="bottom: -6px;">
                                        <!-- checkbox -->
                                        @if($role['countData'] != 0)
                                            @foreach($role['data'] as $key => $value)
                                                <label>
                                                    <input type="radio" name="role_id" class="minimal" value="{{ $value['id'] }}" {{ @in_array($value['id'], $data['role_id']) ? 'checked' : '' }}>
                                                    {{ $value['name'] }}
                                                </label>
                                                <br>
                                            @endforeach
                                        @else
                                            <div class="input-group">
                                                <p>Data role is empty, please add data role first.</p>
                                            </div>
                                        @endif
                                    </div>
                                </div>
                                @if (isset($data['id']))
                                    <div class="form-group">
                                        <label for="status" class="col-sm-3 control-label">Status</label>

                                        <div class="col-sm-9" style="bottom: -6px;">
                                            <!-- radio -->
                                            <label style="min-width: 130px;">
                                                <input type="radio" name="status" class="minimal" value="1" {{ @$data['status'] == 1 ? 'checked' : '' }}>
                                                Aktif
                                            </label>
                                            <label>
                                                <input type="radio" name="status" class="minimal" value="0" {{ @$data['status'] == 0 ? 'checked' : '' }}>
                                                Non Aktif
                                            </label>
                                        </div>
                                    </div>
                                @endif
                                {{--<hr>--}}
                                {{--<div class="form-group">--}}
                                    {{--<label for="telegram_id" class="col-sm-3 control-label">Telegram ID</label>--}}

                                    {{--<div class="col-sm-9">--}}
                                        <input type="hidden" class="form-control" id="telegram_id" name="telegram_id" placeholder="Telegram ID" value="{{ @$data['telegram_id'] }}">
                                    {{--</div>--}}
                                {{--</div>--}}
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-success pull-right">{{ isset($data['id']) ? "Save" : "Submit" }}</button>
                            </div>
                            <!-- /.box-footer -->
                        </form>
                    </div>
                </div>

            </div><!-- /.row -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <script>
        // iCheck for checkbox and radio inputs
        $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
            checkboxClass: 'icheckbox_minimal-green',
            radioClass   : 'iradio_minimal-green'
        })

        $(function () {
            var checkAll = $('input.check_all');
            var checkboxes = $('input.check');

            $('input[type="checkbox"].minimal, input[type="radio"].minimal').iCheck({
                checkboxClass: 'icheckbox_minimal-green',
                radioClass   : 'iradio_minimal-green'
            });

            if(checkboxes.filter(':checked').length == checkboxes.length) {
                checkAll.prop('checked', true);
            } else {
                checkAll.prop('checked', false);
            }

            checkAll.iCheck('update');

            checkAll.on('ifChecked ifUnchecked', function(event) {
                if (event.type == 'ifChecked') {
                    checkboxes.iCheck('check');
                } else {
                    checkboxes.iCheck('uncheck');
                }
            });

            checkboxes.on('ifChanged', function(event){
                if(checkboxes.filter(':checked').length == checkboxes.length) {
                    checkAll.prop('checked', true);
                } else {
                    checkAll.prop('checked', false);
                }

                checkAll.iCheck('update');
            });
        });
    </script>
@endsection

resources/views/botUser/list.blade.php
@extends('main')

@section('content')
    <style>
        .deleteForm {
            all: unset;
        }

        .example-modal .modal {
            position: relative;
            top: auto;
            bottom: auto;
            right: auto;
            left: auto;
            display: block;
            z-index: 1;
        }

        .example-modal .modal {
            background: transparent !important;
        }
    </style>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                <i class="fa fa-dot-circle-o"></i> Bot User
            </h1>
            <br>
            <ol class="breadcrumb">
                <?php $segments = ''; ?>
                @foreach(Request::segments() as $segment)
                    <?php $segments .= '/'.$segment; ?>
                    <li>
                        <a href="{{ $segments }}"><i>{{ ucfirst($segment) }}</i></a>
                    </li>
                @endforeach
            </ol>
        </section>
        <!-- Main content -->
        <section class="content container-fluid">

            @if(session()->get('success'))
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert alert-success alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <h4><i class="icon fa fa-check"></i>Success</h4>
                            {{ session()->get('success') }}
                        </div>
                    </div>
                </div>
            @endif

            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="row">
                        <div class="col-md-12">
                            <div class="alert alert-danger alert-dismissible">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                <h4><i class="icon fa fa-close"></i>Failed</h4>
                                {{ $error }}
                            </div>
                        </div>
                    </div>
                @endforeach
            @endif

            <!-- Content -->
            <div class='row'>
                <div class='col-md-12'>
                    <!-- Box -->
                    <div class="box box-default">
                        <div class="box-header with-border">
                            <div class="col-md-10">

                            </div>
                            <div class="col-md-2">
                                <a href="{{ route('botuser.create') }}" class="btn btn-block btn-success"><i class="fa fa-plus"></i> Add Data</a>
                            </div>
                        </div>
                        <div class="box-body">
                            <table id="data" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Username</th>
                                    <th>Role</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {{--Data--}}
                                <?php $i = 1 ?>
                                @foreach($list as $key => $data)
                                    <tr>
                                        <td>{{ $i++ }}</td>
                                        <td>{{ $data['name'] }}</td>
                                        <td>{{ $data['username'] }}</td>
                                        <td>{{ $command->firstwhere('id', $data['role_id'])['name'] }}</td>
                                        <td class="text-center"><span class="label bg-{{ $data['status']==1? 'green' : 'red' }}">{{ $data['status']==1? 'Active' : 'Non Active' }}</span></td>
                                        <td class="text-center">
                                            <button class="btn btn-sm btn-info detailPage" data-toggle="modal" data-target="#modal-default" data_id="{{ $data['id'] }}"><i class="fa fa-info-circle"></i></button>
                                            <a href="{{ route('botuser.edit', $data['id']) }}" class="btn btn-sm btn-primary"><i class="fa fa-pencil-square-o"></i></a>
                                            <form class="deleteForm" action="{{ route('botuser.destroy', $data['id']) }}" row="{{ $data['name'] }}" method="POST">
                                                @method('DELETE')
                                                @csrf
                                                <button class="btn btn-sm btn-danger" id="btn-form"><i class="fa fa-trash-o"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                {{--End Data--}}
                                </tbody>
                            </table>
                        </div><!-- /.box-body -->

                    </div><!-- /.box -->
                </div><!-- /.col -->

            </div><!-- /.row -->

            <div class="modal fade" id="modal-default">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title"></h4>
                        </div>
                        <div class="modal-body">
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="name" class="col-sm-3 control-label">Name</label>

                                    <div class="col-sm-9">
                                        <p id="name" class="control-label">Name</p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="username" class="col-sm-3 control-label">Username</label>

                                    <div class="col-sm-9">
                                        <p id="username" class="control-label">Username</p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="role" class="col-sm-3 control-label">Role</label>

                                    <div class="col-sm-9">
                                        <p id="role" class="control-label">Role</p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="telegram_id" class="col-sm-3 control-label">Telegram ID</label>

                                    <div class="col-sm-9">
                                        <p id="telegram_id" class="control-label">Telegram ID</p>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="status" class="col-sm-3 control-label">Status</label>

                                    <div class="col-sm-9">
                                        <span id="status" class="label"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">

                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <script>
        jQuery(document).ready(function(){
            jQuery('.detailPage').click(function(e){
                e.preventDefault();
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                    }
                });
                jQuery.ajax({
                    url: "{{ url('botuser') }}" + "/" + $(this).attr('data_id'),
                    method: 'GET',
                    success: function(result) {
                        console.log(result);
                        $('.modal-title').text("Detail Bot User");
                        $('#name').text(result.data.name ? result.data.name : '-');
                        $('#username').text(result.data.username ? result.data.username : '-');
                        $('#role').text(result.data.role_id ? result.data.role_id : '-');
                        $('#telegram_id').text(result.data.telegram_id ? result.data.telegram_id : '-');
                        if (result.data.status === 1) {
                            $('#status').text("Active");
                            $('#status').addClass('bg-green');
                        } else {
                            $('#status').text("Non Active");
                            $('#status').addClass('bg-red');
                        }

                    }
                });
            });
        });

        $(".deleteForm").on("submit", function(){
            return confirm("Are you sure permanently delete " + this.getAttribute("row") + " ?");
        });
    </script>
@endsection